blank_issues_enabled: false
contact_links:
  - name: Zube Board (Backlog / Sprint)
    url: https://zube.io/                         # put your project URL
    about: Please move created issues into the correct Zube pipeline.
