blank_issues_enabled: false
contact_links:
  - name: Zube Board (connect after GitHub setup)
    url: https://zube.io/            # put your real Zube project URL later
    about: Move created issues into the correct Zube pipeline after linking.
